on:
  push:
    branches:
        - main  # Change to your main branch name
jobs:
  build:
    runs-on: ubuntu-latest
    name: script/cibuild
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Use the appropriate Python version

      - name: Set up Ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
          bundler-cache: true

      # - name: build bootstrap
      #   run: script/bootstrap

      - name: test
        run: script/cibuild
